					db ?									; 5154
					db ?									; 5155
					db ?									; 5156
					db ?									; 5157
					db ?									; 5158
					db ?									; 5159
					db ?									; 515A
					db ?									; 515B
					db ?									; 515C
					db ?									; 515D
					db ?									; 515E
					db ?									; 515F
word_5160:			dw ?									; 5160
word_5162:			dw ?									; 5162, temporary storage for data segment (0F6C)
word_5164:			dw ?									; 5164
word_5166:			dw ?									; 5166
word_5168:			dw ?									; 5168
word_516A:			dw ?									; 516A
counter:			db ?									; 516C
byte_516D:			db ?									; 516D
word_516E:			dw ?									; 516E
byte_5170:			db ?									; 5170
					db 90h
idx:				dw ?									; 5172
word_5174:			dw ?									; 5174
word_5176:			dw ?									; 5176
