                    rb 12                                   ; 5154
word_5160:          dw ?                                    ; 5160: ES
word_5162:          dw data_seg                             ; 5162: DS
word_5164:          dw ?                                    ; 5164: SS
word_5166:          dw test_seg                             ; 5166
word_5168:          dw test_seg                             ; 5168
word_516A:          dw ?                                    ; 516A
counter:            db ?                                    ; 516C
byte_516D:          db ?                                    ; 516D
word_516E:          dw ?                                    ; 516E
byte_5170:          db ?                                    ; 5170
                    db 90h
idx:                dw ?                                    ; 5172
word_5174:          dw ?                                    ; 5174
word_5176:          dw ?                                    ; 5176
